require('plugins.install-plugins')
require('plugins.gruvbox')
require('plugins.lualine')
require('plugins.barbar')
require('plugins.telescope')
require('plugins.nvim-lspconfig')
require('plugins.rust-tools')
-- require('plugins.nvim-cmp')
require('plugins.kommentary')
require('plugins.treesitter')
