require('plugins.install-plugins')
-- require('plugins.install-plugins-vimscript')
require('plugins.gruvbox')
-- require('plugins.tokyonight')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.nvim-lspconfig')
require('plugins.rust-tools')
-- require('plugins.nvim-cmp')
require('plugins.kommentary')
